[package]
name = "cargo-bundle-licenses"
version = "0.1.0"
edition = "2018"
readme = "README.md"
license = "MIT/Apache-2.0"
description = "Bundle licensing of dependencies"
repository = "https://github.com/sstadick/cargo-bundle-licenses"
keywords = ["cargo", "licensing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
cargo_metadata = "0.14.0"
env_logger = "0.9.0"
log = "0.4.14"
slug = "0.1.4"
structopt = "0.3.22"
toml = "0.5.8"


[build-dependencies]
built = "0.5.1"
